print("\nPlease enter the following information:\n")

first_name = input("First name: ").title()
last_name = input("Last name: ").upper()
email = input("Email address: ").lower()
phone_number = input("Phone number: ")
job = input("Job title: ").title()
id_number = input("ID number: ")
hair_color = input("Hair color: ").title()
eye_color = input("Eye color: ").title()
month_started = input("Month started: ").title()
training = input("Completed advanced training(Yes/No): ").title()

print("\nThe ID Card is:\n----------------------------------------")
print(f"{last_name}, {first_name}")
print(job)
print(f"ID: {id_number}\n")
print(email)
print(phone_number)
print(f"\n{'Hair: ' + hair_color:<20} Eyes: {eye_color}")
print(f"{'Month: ' + month_started:<20} Training: {training}")
print("----------------------------------------")